os: linux
dist: focal
arch: arm64-graviton2
virt: lxd
group: edge
language: c
compiler:
- gcc
branches:
  only:
  - ad
  - "/^v.*$/"
addons:
  apt:
    packages:
    - fakeroot
    - p7zip-full
    - libtool-bin
    - gperf
    - texinfo
    - python-docutils
    - autopoint
    - shellcheck
    - cpio
    - libltdl-dev
    - gettext
before_script:
- "./trunk/tools/shellcheck.sh"
- mkdir -p /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x && mkdir -p /opt/images/
- rm -rf toolchain-mipsel/ && mv -f * .[^.]* /opt/rt-n56u
- curl -LO $toolchain_url && tar -xf $toolchain_pkg -C /opt/rt-n56u/toolchain-mipsel/toolchain-3.4.x
- ls -Alh /opt/rt-n56u && cd /opt/rt-n56u/trunk/
script:
- for m in $targets; do fakeroot ./build_firmware_ci $m;
  if [ $? = 0 ]; then cp -f images/*.trx /opt/images/$m.trx; else exit 1; fi;
  ./clear_tree_simple >/dev/null 2>&1; done
after_script:
- GIT_VERSION=`git rev-parse --short=7 HEAD 2>/dev/null` && [ -n "$GIT_VERSION" ]
  && image_name=images_${build_variant}_${GIT_VERSION} || image_name=images_${build_variant}
- cd /opt/images; md5sum *.trx |tee md5sum.txt; 7z a -mx=9 ${image_name}.7z ./*
- curl -m 120 -F file=@${image_name}.7z https://file.io/?expires=3d ; echo
- 'curl -m 120 -H ''Max-Days: 3'' --upload-file ./${image_name}.7z https://transfer.sh/${image_name}.7z ; echo'
env:
  jobs:
  - build_variant=mt7621 targets="K2P K2P-5.0"
  - build_variant=mt7620 targets="K2"
  - build_variant=mt7628 targets="HC5761A"
  global:
  - toolchain_pkg="aarch64_mipsel-linux-uclibc.tar.xz"
  - toolchain_url="https://github.com/896660689/builb--padavan/releases/download/padavan/$toolchain_pkg"
git:
  depth: 1
deploy:
  provider: releases
  token:
    secure: "GGHrKCkSvtNDttSd6jMV8cm6Cqv0LvpKz4s55N/Nl3WduMV0W/sixAquQ6a3/MNIvfosVsE9J+etT6lIeKap1X1awnLzpTU2shi7jJN7pBwh/aomsKPpuGFF4w56cQKJqi7It3l6T/Xd02r059mbQkfx3H0MyjXlwcIf1rPhtnksxAQ7tFYmLMuCClahgN42+JL6Brmy2gkL3kY7W0rtUd6SZ7H16gTW+Rm1eJMU1kBMku9wz3cgu9jLuBrgE6RgDDE5nMfVimJbEWo2pkVJH2sTWu3nvZ3S+3WNHNJvkpb08Sx7NCB9IYrWQgzNHRd0YkptksDJ1qZNepaO03uHPZfscLl9O8UinJpkp1DCwnQK9yQ3SbbZy2S1i492c+93z2reTSrXu+PIe1U12tVmXx5Vk7RbWuErHW9+Uq1fYbqK9GvPtZbpHusiphA+5WeaNyRCO+9axjn9pGVnsaBWjyH2pKV4N7o1pQIydmPgxqmQe45y/oZ0rMIsLyUEImvCkDg4tfig22NierCbhT+LFnu1fHE1RpS2kzrwXmy/w5UNVAP3zF+hS59YVuSnRgP0sKuRZyTeHHGrIgNAdAv5fSjsGgHtYaKnMXoypXMETZAJFdnDGOJM5AYNhVAgWd59YcF4AaF0xZwz0w8t9q4rq1p50KJxu6sZW5XvhlqrOr0="
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file: "/opt/images/*.trx"
  on:
    repo: 896660689/rt-n56u
    tags: true

